DROP TABLE IF EXISTS DRIVER;

CREATE TABLE DRIVER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  phone_number VARCHAR(250) NOT NULL,
  license_number VARCHAR(250) NOT NULL,
  car_number VARCHAR(250) NOT NULL,
  latitude DECIMAL(10,8),
  longitude DECIMAL(11,8)
);